version: '3.8'
services:
  server:
    container_name: messenger-app-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - logs:/app/logs
      - /app/node_modules
    env_file:
      - ./server/.env
    environment:
      - DOCKER_ENVIRONMENT=true
    restart: unless-stopped

  client:
    container_name: messenger-app-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true        
    env_file:
      - ./client/.env
    environment:
      - DOCKER_ENVIRONMENT=true
    depends_on:
      - server
    restart: unless-stopped

volumes:
  logs: